In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier

In [2]:
X_data= np.random.rand(50,10)
print(X_data)

[[0.90832452 0.69876507 0.94918325 0.63208799 0.08554456 0.44645727
  0.53088615 0.67571603 0.93408045 0.69079866]
 [0.20721499 0.24514417 0.64085361 0.25420394 0.0857561  0.09293282
  0.22310998 0.57090026 0.77761477 0.72689162]
 [0.78733087 0.28677543 0.52687336 0.79289859 0.79682651 0.21969969
  0.24149837 0.61510723 0.77650337 0.1981308 ]
 [0.98763144 0.93187411 0.81181592 0.21459105 0.28403272 0.01699659
  0.14372614 0.06541052 0.61625036 0.25273881]
 [0.28007115 0.01559343 0.07434854 0.57686262 0.59376553 0.86399648
  0.27666101 0.20171362 0.85476464 0.95799005]
 [0.63160315 0.9788547  0.38662602 0.38877938 0.61499002 0.62738351
  0.28104386 0.96179568 0.18923596 0.1293748 ]
 [0.02864676 0.57370102 0.78750521 0.69166135 0.22263923 0.8323202
  0.02073601 0.54612925 0.40944858 0.62017488]
 [0.76905868 0.6950206  0.28509119 0.04998787 0.69952307 0.97580132
  0.45585064 0.96412201 0.5126082  0.56598931]
 [0.40549848 0.18524359 0.86308195 0.43559542 0.62324072 0.3377047
  0.7256121  0

In [3]:
y_labels= np.random.randint(0,2,50)
print(y_labels)

[0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 0 0 1 0]


In [4]:
scaler= MinMaxScaler()
X_data_normalized = scaler.fit_transform(X_data)

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X_data_normalized,y_labels,test_size=0.3,random_state=42)

In [6]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
y_pred=knn.predict(X_test)
print(y_pred)

[1 1 0 0 0 1 0 1 1 0 1 1 0 0 0]


In [27]:
cm2=confusion_matrix(y_test,y_pred)
print(cm2)

[[3 4]
 [5 3]]


In [9]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.4


In [20]:
dt_classifier=DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
y_pred2=dt_classifier.predict(X_test)
print(y_pred2)

[1 0 1 0 1 1 0 0 0 0 1 1 1 0 0]


In [28]:
cm=confusion_matrix(y_test,y_pred2)
print(cm)

[[3 4]
 [5 3]]


In [26]:
accuracy2=accuracy_score(y_test,y_pred2)
print(accuracy2)

0.4


In [31]:
X_data,y_labels=make_classification(n_samples=1000,n_features=20,n_informative=2,n_classes=2,random_state=42)

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X_data,y_labels,test_size=0.3,random_state=42)

In [33]:
knn2=KNeighborsClassifier(n_neighbors=3)
knn2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [34]:
y_pred3=knn2.predict(X_test)
print(y_pred3)

[0 0 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 0 1 0
 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 0 1 0
 0 1 0 1 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 1 0 0 0
 0 0 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 0
 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1
 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 0
 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0
 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0
 0 1 0 0]


In [35]:
cm3=confusion_matrix(y_test,y_pred3)
print(cm3)

[[121  24]
 [ 39 116]]


In [36]:
accuracy3=accuracy_score(y_test,y_pred3)
print(accuracy3)

0.79


In [38]:
dt_classifier4=DecisionTreeClassifier(random_state=42)
dt_classifier4.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [40]:
y_pred4=dt_classifier4.predict(X_test)
print(y_pred4)

[1 1 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 1 0 0
 0 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 0 0
 0 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0
 0 1 1 1 1 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0
 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 1 0 0 0
 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0
 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0
 0 1 0 1]


In [41]:
cm4=confusion_matrix(y_test,y_pred4)
print(cm4)

[[124  21]
 [ 22 133]]


In [42]:
accuracy4=accuracy_score(y_test,y_pred4)
print(accuracy4)

0.8566666666666667


In [ ]:
#New                      #New                               #New                                    #New                             #New                          #New    

In [ ]:
#New                      #New                               #New                                    #New                             #New                          #New    

In [ ]:
#New                      #New                               #New                                    #New                             #New                          #New    

In [ ]:
#New                      #New                               #New                                    #New                             #New                          #New    

In [ ]:
#New                      #New                               #New                                    #New                             #New                          #New    

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier,StackingClassifier,VotingClassifier,GradientBoostingClassifier


#1


X_data,y_labels=make_classification(n_samples=1000,n_features=20,n_informative=2,n_classes=2,random_state=42)


#2


X_train,X_test,y_train,y_test=train_test_split(X_data,y_labels,test_size=0.3,random_state=42)

#3

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)


#4


y_pred=knn.predict(X_test)



#5


cm2=confusion_matrix(y_test,y_pred)
print(cm2)


#6


accuracy=accuracy_score(y_test,y_pred)
print(accuracy)


#7


dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)


#8


y_pred2=dt_classifier.predict(X_test)



#9


cm=confusion_matrix(y_test,y_pred2)
print(cm)


#10


accuracy2=accuracy_score(y_test,y_pred2)
print(accuracy2)


[[121  24]
 [ 39 116]]
0.79
[[124  21]
 [ 22 133]]
0.8566666666666667


0.84

In [4]:
bagging_model= BaggingClassifier(base_estimator=dt,n_estimators=10,random_state=42)
bagging_model.fit(X_train,y_train)
bagging_pred=bagging_model.predict(X_test)
accuracy_score(y_test,bagging_pred)

0.84

In [5]:
stacking_model=StackingClassifier(estimators=[('knn',knn),('dt',dt)],final_estimator=KNeighborsClassifier())
stacking_model.fit(X_train,y_train)
stacking_pred=stacking_model.predict(X_test)
accuracy_score(y_test,stacking_pred)

0.8566666666666667

In [6]:
boosting_model=GradientBoostingClassifier(n_estimators=100,random_state=42)
boosting_model.fit(X_train,y_train)
boosting_pred=boosting_model.predict(X_test)
accuracy_score(y_test,boosting_pred)

0.87

In [7]:
voting_model=VotingClassifier(estimators=[('knn',knn),('dt',dt)],voting='hard')
voting_model.fit(X_train,y_train)
voting_pred=voting_model.predict(X_test)
accuracy_score(y_test,voting_pred)

0.84